name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/home/mybplus/htdocs/mybplus.com

            # Pull latest changes
            git reset --hard
            git pull

            # Update environment variables
            echo "${{ secrets.APP_ENV }}" > .env

            # Install dependencies
            npm install

            # Build the Next.js app
            npm run build

            # Check if PM2 process exists
            if pm2 list | grep -q "my_bookkeeping_butler"; then
              pm2 restart my_bookkeeping_butler
            else
              pm2 start npm --name "my_bookkeeping_butler" -- start
            fi

            # Save PM2 process list to auto-start on reboot
            pm2 save