name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to project folder
            cd ~/home/mybplus/htdocs/mybplus.com

            # Pull latest code
            git reset --hard
            git pull

            # Write .env before build
            echo "${{ secrets.APP_ENV }}" > .env

            # Install dependencies
            npm install

            # Build Next.js app
            npm run build

            # PM2 runtime variables
            PM2_APP_NAME="my_bookkeeping_butler"
            BREVO_API_KEY="${{ secrets.BREVO_API_KEY }}"

            # Start or restart PM2 process
            if pm2 list | grep -q "$PM2_APP_NAME"; then
              pm2 restart $PM2_APP_NAME --update-env
            else
              pm2 start npm --name "$PM2_APP_NAME" -- start
            fi

            # Save PM2 process list to persist across reboots
            pm2 save