name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://mybplus.com/

    permissions:
      deployments: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: create-deployment
        with:
          token: ${{ github.token }}
          environment-url: https://mybplus.com/
          description: Deploying to production VPS
          environment: production
          initial-status: in_progress

      - name: Deploy over SSH
        id: deploy-ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            # Use correct Node version
            nvm install 21
            nvm use 21

            cd /home/mybplus/htdocs/mybplus.com/my_bookkeeping_butler

            # Pull latest code
            git reset --hard
            git pull origin main

            # Ensure env file exists
            if [ ! -f .env.production ]; then
              echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> .env.production
              echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.production
            fi

            # Install dependencies
            npm install

            # Build Next.js
            npm run build

            # Restart PM2
            pm2 delete my_bookkeeping_butler || true
            pm2 start npm --name "my_bookkeeping_butler" -- run start

            # Save PM2 config
            pm2 save
            pm2 update

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ github.token }}
          environment-url: https://mybplus.com/
          description: Successfully deployed to production VPS
          environment: production
          initial-status: success
          log-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ github.token }}
          environment-url: https://mybplus.com/
          description: Deployment to production VPS failed
          environment: production
          initial-status: failure
          log-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}