name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1 — Create GitHub Deployment
      - name: Create GitHub Deployment
        id: create_deployment
        uses: peter-evans/create-deployment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          description: "Deploying latest changes to VPS"
          transient_environment: false
          production_environment: true
          auto_merge: false

      # Step 2 — Deploy to VPS over SSH
      - name: Deploy over SSH
        id: deploy_ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            nvm install 21
            nvm use 21

            cd /home/mybplus/htdocs/mybplus.com/my_bookkeeping_butler

            git reset --hard
            git pull origin main

            if [ ! -f .env.local ]; then
              echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> .env.local
            fi

            npm ci
            npm run build

            pm2 delete my_bookkeeping_butler || true
            pm2 start npm --name "my_bookkeeping_butler" -- run start
            pm2 save
            pm2 update

      # Step 3 — Update Deployment Status
      - name: Mark Deployment as Successful
        if: success()
        uses: peter-evans/create-deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: success
          environment_url: https://mybplus.com

      - name: Mark Deployment as Failed
        if: failure()
        uses: peter-evans/create-deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
          state: failure
