name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            # Use correct Node version
            nvm install 21
            nvm use 21

            cd /home/mybplus/htdocs/mybplus.com/my_bookkeeping_butler

            # Pull latest code
            git reset --hard
            git pull origin main

            # Ensure env file exists
            if [ ! -f .env.local ]; then
              echo "BREVO_API_KEY=${{ secrets.BREVO_API_KEY }}" >> .env.local
            fi

            # Install dependencies
            npm install

            # Build Next.js
            npm run build

            # Restart PM2 with correct Node interpreter
            pm2 delete my_bookkeeping_butler || true
            pm2 start npm --name "my_bookkeeping_butler" --cwd /home/mybplus/htdocs/mybplus.com/my_bookkeeping_butler -- run start

            # Save PM2 config
            pm2 save
            pm2 update

