name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- SSH Pre-Check Step ---
      - name: Test SSH connection to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "✅ SSH connection successful"
            whoami
            hostname

      # --- Deployment Step ---
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/home/mybplus/htdocs/mybplus.com
            git reset --hard
            git pull

            # Write .env before build
            echo "${{ secrets.APP_ENV }}" > .env

            npm install
            npm run build

            PM2_APP_NAME="my_bookkeeping_butler"
            BREVO_API_KEY="${{ secrets.BREVO_API_KEY }}"

            if pm2 list | grep -q "$PM2_APP_NAME"; then
              pm2 restart $PM2_APP_NAME --update-env
            else
              pm2 start npm --name "$PM2_APP_NAME" -- start
            fi

            pm2 save